use leituramiga;

INSERT INTO categoria (descricao) VALUES ('Fantasia');
INSERT INTO categoria (descricao) VALUES ('Ficção Científica');
INSERT INTO categoria (descricao) VALUES ('Romance');
INSERT INTO categoria (descricao) VALUES ('Terror');
INSERT INTO categoria (descricao) VALUES ('Biografia');
INSERT INTO categoria (descricao) VALUES ('Autoajuda');
INSERT INTO categoria (descricao) VALUES ('História');
INSERT INTO categoria (descricao) VALUES ('Aventura');
INSERT INTO categoria (descricao) VALUES ('Suspense');
INSERT INTO categoria (descricao) VALUES ('Mistério');
INSERT INTO categoria (descricao) VALUES ('Clássicos');
INSERT INTO categoria (descricao) VALUES ('Drama');
INSERT INTO categoria (descricao) VALUES ('Poesia');
INSERT INTO categoria (descricao) VALUES ('Infantil');
INSERT INTO categoria (descricao) VALUES ('Distopia');
INSERT INTO categoria (descricao) VALUES ('Fantasia Urbana');
INSERT INTO categoria (descricao) VALUES ('Fábula');
INSERT INTO categoria (descricao) VALUES ('Graphic Novel');
INSERT INTO categoria (descricao) VALUES ('Humor');
INSERT INTO categoria (descricao) VALUES ('Memórias');
INSERT INTO categoria (descricao) VALUES ('Ensaios');
INSERT INTO categoria (descricao) VALUES ('Contos');
INSERT INTO categoria (descricao) VALUES ('Crônicas');
INSERT INTO categoria (descricao) VALUES ('Viagem');
INSERT INTO categoria (descricao) VALUES ('Gastronomia');
INSERT INTO categoria (descricao) VALUES ('Negócios');
INSERT INTO categoria (descricao) VALUES ('Saúde e Bem-Estar');
INSERT INTO categoria (descricao) VALUES ('Educação');
INSERT INTO categoria (descricao) VALUES ('Filosofia');
INSERT INTO categoria (descricao) VALUES ('Religião');
INSERT INTO categoria (descricao) VALUES ('Tecnologia');
INSERT INTO categoria (descricao) VALUES ('Ciência');
INSERT INTO categoria (descricao) VALUES ('Política');
