se leituramiga;

INSERT INTO categoria (descricao) VALUES ('Fantasia');
INSERT INTO categoria (descricao) VALUES ('Ficção Científica');
INSERT INTO categoria (descricao) VALUES ('Romance');
INSERT INTO categoria (descricao) VALUES ('Terror');
INSERT INTO categoria (descricao) VALUES ('Biografia');
INSERT INTO categoria (descricao) VALUES ('Autoajuda');
INSERT INTO categoria (descricao) VALUES ('História');
INSERT INTO categoria (descricao) VALUES ('Aventura');
INSERT INTO categoria (descricao) VALUES ('Suspense');
INSERT INTO categoria (descricao) VALUES ('Mistério');
INSERT INTO categoria (descricao) VALUES ('Clássicos');
INSERT INTO categoria (descricao) VALUES ('Drama');
INSERT INTO categoria (descricao) VALUES ('Poesia');
INSERT INTO categoria (descricao) VALUES ('Infantil');
INSERT INTO categoria (descricao) VALUES ('Distopia');
INSERT INTO categoria (descricao) VALUES ('Fantasia Urbana');
INSERT INTO categoria (descricao) VALUES ('Fábula');
INSERT INTO categoria (descricao) VALUES ('Graphic Novel');
INSERT INTO categoria (descricao) VALUES ('Humor');
INSERT INTO categoria (descricao) VALUES ('Memórias');
INSERT INTO categoria (descricao) VALUES ('Ensaios');
INSERT INTO categoria (descricao) VALUES ('Contos');
INSERT INTO categoria (descricao) VALUES ('Crônicas');
INSERT INTO categoria (descricao) VALUES ('Viagem');
INSERT INTO categoria (descricao) VALUES ('Gastronomia');
INSERT INTO categoria (descricao) VALUES ('Negócios');
INSERT INTO categoria (descricao) VALUES ('Saúde e Bem-Estar');
INSERT INTO categoria (descricao) VALUES ('Educação');
INSERT INTO categoria (descricao) VALUES ('Filosofia');
INSERT INTO categoria (descricao) VALUES ('Religião');
INSERT INTO categoria (descricao) VALUES ('Tecnologia');
INSERT INTO categoria (descricao) VALUES ('Ciência');
INSERT INTO categoria (descricao) VALUES ('Política');
INSERT INTO categoria (descricao) VALUES ('Música');
INSERT INTO categoria (descricao) VALUES ('Esportes');
INSERT INTO categoria (descricao) VALUES ('Artes');
INSERT INTO categoria (descricao) VALUES ('Natureza');
INSERT INTO categoria (descricao) VALUES ('Psicologia');
INSERT INTO categoria (descricao) VALUES ('Ecologia');
INSERT INTO categoria (descricao) VALUES ('Finanças Pessoais');
INSERT INTO categoria (descricao) VALUES ('Direito');
INSERT INTO categoria (descricao) VALUES ('Engenharia');
INSERT INTO categoria (descricao) VALUES ('Arquitetura');
INSERT INTO categoria (descricao) VALUES ('Moda');
INSERT INTO categoria (descricao) VALUES ('Fotografia');
INSERT INTO categoria (descricao) VALUES ('Jornalismo');
INSERT INTO categoria (descricao) VALUES ('Literatura Estrangeira');
INSERT INTO categoria (descricao) VALUES ('Mitologia');
INSERT INTO categoria (descricao) VALUES ('Auto-Biografia');
INSERT INTO categoria (descricao) VALUES ('Espiritualidade');
INSERT INTO categoria (descricao) VALUES ('Ficção Policial');
INSERT INTO categoria (descricao) VALUES ('Realismo Mágico');
INSERT INTO categoria (descricao) VALUES ('Sociologia');
INSERT INTO categoria (descricao) VALUES ('Mangás');
INSERT INTO categoria (descricao) VALUES ('História em Quadrinhos');
